services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U wallet_user -d wallet" ]
      interval: 2s
      timeout: 2s
      retries: 30
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ../api
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wallet
      SPRING_DATASOURCE_USERNAME: wallet_user
      SPRING_DATASOURCE_PASSWORD: wallet_password
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/wallet-api/api/v1/wallet/health | grep '\"status\"\\s*:\\s*\"UP\"' >/dev/null || exit 1" ]
      interval: 3s
      timeout: 3s
      retries: 60

volumes:
  pgdata:
