version: "3.9"
services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U wallet -d wallet" ]
      interval: 2s
      timeout: 2s
      retries: 30
    ports: [ "5432:5432" ]

  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wallet
      SPRING_DATASOURCE_USERNAME: wallet
      SPRING_DATASOURCE_PASSWORD: wallet
      SERVER_PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    ports: [ "8080:8080" ]
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/wallet-api/actuator/health | grep UP || exit 1" ]
      interval: 3s
      timeout: 2s
      retries: 60
