services:
  app:
    environment:
      - LOGGING_FILE_PATH=/var/log/app
    volumes:
      - applogs:/var/log/app

  loki:
    image: grafana/loki:2.9.8
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3100/ready" ]
      interval: 5s
      timeout: 3s
      retries: 20

  promtail:
    image: grafana/promtail:2.9.8
    command: [ "-config.file=/etc/promtail/config.yml" ]
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml:ro
      - applogs:/var/log/app:ro
    depends_on:
      loki:
        condition: service_healthy

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
      - prometheus

  prometheus:
    image: prom/prometheus:v2.53.0
    command: [ "--config.file=/etc/prometheus/prometheus.yml" ]
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

volumes:
  applogs:
  loki-data:
  grafana-data:
