version: "3.9"
services:
  lb:
    image: nginx:1.27-alpine
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost/ | head -n1 >/dev/null || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 20
