services:
  k6:
    image: grafana/k6:0.52.0
    environment:
      BASE_URL: ${BASE_URL:-http://lb}
      K6_SCRIPT: ${K6_SCRIPT:-deposits.js}
    command: [ "run", "/scripts/${K6_SCRIPT}" ]
    volumes:
      - ../loadtest:/scripts:ro
