version: "3.9"
services:
  loki:
    image: grafana/loki:2.9.8
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3100/ready" ]
      interval: 5s
      timeout: 3s
      retries: 20

  promtail:
    image: grafana/promtail:2.9.8
    command: [ "-config.file=/etc/promtail/config.yml" ]
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
    depends_on:
      loki:
        condition: service_healthy
