spring:
  profiles:
    active: prod
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  security:
    user:
      password: ${SECURITY_PASSWORD:} # No default password in production

wallet:
  app:
    api-docs:
      enabled: false

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    com.bank.wallet: INFO
    org.hibernate: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type: ERROR
    org.hibernate.jpa: ERROR
    org.hibernate.engine: ERROR
    org.springframework.jdbc: WARN
    org.springframework.jdbc.core: WARN
    com.zaxxer.hikari: INFO
    root: WARN
  file:
    name: /var/log/wallet-app/wallet-app.log
